export const REQUIRED_AUTHORIZATION = `REQUIRED AUTHORIZATION`;
export const LOGOUT = `LOGOUT`;
export const SET_IS_AUTH_CHECKED = `SET_IS_AUTH_CHECKED`;
export const REDIRECT_TO_ROUTE = `REDIRECT TO ROUTE`;
